In [2]:
import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [3]:
#import dataset
diabetes_df = pd.read_csv('./dataset/Diabetestype.csv')
diabetes_df.head(10) #melihat dataframe diabetes

Age  BS Fast  BS pp  Plasma R  Plasma F  HbA1c    Type  Class
0   50      6.8    8.8      11.2       7.2     62   Type1      1
1   31      5.2    6.8      10.9       4.2     33  Normal      0
2   32      6.8    8.8      11.2       7.2     62   Type1      1
3   21      5.7    5.8      10.7       4.8     49  Normal      0
4   33      6.8    8.8      11.2       7.2     62   Type1      1
5   30      5.2    7.4       8.7       5.6     41  Normal      0
6   26      5.8    4.2      11.4       8.4     53   Type2      1
7   29      5.2    7.4       8.7       5.6     41  Normal      0
8   53      6.9    8.4      11.2       7.2     62   Type2      1
9   54      6.3    4.2      12.2       7.8     57   Type2      1

In [4]:
diabetes_df.info() #cek keterangan dari objek dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1009 entries, 0 to 1008
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1009 non-null   int64  
 1   BS Fast   1009 non-null   float64
 2   BS pp     1009 non-null   float64
 3   Plasma R  1009 non-null   float64
 4   Plasma F  1009 non-null   float64
 5   HbA1c     1009 non-null   int64  
 6   Type      1009 non-null   object 
 7   Class     1009 non-null   int64  
dtypes: float64(4), int64(3), object(1)
memory usage: 63.2+ KB


In [5]:
diabetes_df.describe() #cek mean, median dsb

Age      BS Fast        BS pp     Plasma R     Plasma F  \
count  1009.000000  1009.000000  1009.000000  1009.000000  1009.000000   
mean     33.398414    12.571853     6.659167    10.728741     6.136075   
std      11.633364    12.334019     1.205188     1.436979     1.620659   
min      21.000000     0.000000     4.200000     7.900000     3.900000   
25%      24.000000     5.600000     5.800000    10.200000     4.800000   
50%      29.000000     6.700000     6.800000    10.900000     5.600000   
75%      41.000000    20.000000     7.700000    11.400000     7.800000   
max      81.000000    54.000000     8.800000    13.100000     9.100000   

             HbA1c        Class  
count  1009.000000  1009.000000  
mean     43.481665     0.374628  
std      12.067515     0.484267  
min      28.000000     0.000000  
25%      33.000000     0.000000  
50%      40.000000     0.000000  
75%      53.000000     1.000000  
max      69.000000     1.000000

## Data Cleaning
#### Hapus atribut/fitur Class karena tidak digunakan

In [6]:
diabetes_df

Age  BS Fast  BS pp  Plasma R  Plasma F  HbA1c    Type  Class
0      50      6.8    8.8      11.2       7.2     62   Type1      1
1      31      5.2    6.8      10.9       4.2     33  Normal      0
2      32      6.8    8.8      11.2       7.2     62   Type1      1
3      21      5.7    5.8      10.7       4.8     49  Normal      0
4      33      6.8    8.8      11.2       7.2     62   Type1      1
...   ...      ...    ...       ...       ...    ...     ...    ...
1004   37      0.0    5.6      10.2       5.4     32  Normal      0
1005   23      6.3    4.2      12.2       7.8     57   Type2      1
1006   37     32.0    7.4       8.7       5.6     41  Normal      0
1007   46     19.0    6.3       7.9       3.9     40  Normal      0
1008   25     16.0    6.3       7.9       3.9     40  Normal      0

[1009 rows x 8 columns]

In [7]:
#Dropping the class feature
diabetes_df.drop("Class",1,inplace=True)

In [8]:
diabetes_df

Age  BS Fast  BS pp  Plasma R  Plasma F  HbA1c    Type
0      50      6.8    8.8      11.2       7.2     62   Type1
1      31      5.2    6.8      10.9       4.2     33  Normal
2      32      6.8    8.8      11.2       7.2     62   Type1
3      21      5.7    5.8      10.7       4.8     49  Normal
4      33      6.8    8.8      11.2       7.2     62   Type1
...   ...      ...    ...       ...       ...    ...     ...
1004   37      0.0    5.6      10.2       5.4     32  Normal
1005   23      6.3    4.2      12.2       7.8     57   Type2
1006   37     32.0    7.4       8.7       5.6     41  Normal
1007   46     19.0    6.3       7.9       3.9     40  Normal
1008   25     16.0    6.3       7.9       3.9     40  Normal

[1009 rows x 7 columns]

In [9]:
#import the libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [10]:
#pisahkan antara atribut dan label
X = diabetes_df.drop('Type',1)
y = diabetes_df.iloc[:,-1]

In [11]:
from sklearn.model_selection import KFold
kf_3 = KFold(n_splits=3)
kf_5 = KFold(n_splits=5)
kf_10 = KFold(n_splits=10)

In [12]:
for train_index, test_index in kf_3.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [13]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [14]:
scores_rf = []
for train_index, test_index in kf_5.split(X):
    #print(train_index, test_index)
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=100), X_train, X_test, y_train, y_test))
    

In [15]:
scores_rf

[1.0, 1.0, 1.0, 1.0, 1.0]

In [16]:
#Check the prediction precision and accuracy
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report # evaluasi performa model

for train_index, test_index in kf_5.split(X):
    #print(train_index, test_index)
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    model_rf = RandomForestClassifier(n_estimators=100)
    model_rf.fit(X_train,y_train) # training model/classifier
    y_pred = model_rf.predict(X_test) # melakukan prediksi
    
    print("confusion matrix: \n", confusion_matrix(y_test, y_pred))
    print(classification_report(y_test,y_pred))
    
    print("=======================================================")

confusion matrix: 
 [[122   0   0]
 [  0  48   0]
 [  0   0  32]]
              precision    recall  f1-score   support

      Normal       1.00      1.00      1.00       122
       Type1       1.00      1.00      1.00        48
       Type2       1.00      1.00      1.00        32

    accuracy                           1.00       202
   macro avg       1.00      1.00      1.00       202
weighted avg       1.00      1.00      1.00       202

confusion matrix: 
 [[123   0   0]
 [  0  35   0]
 [  0   0  44]]
              precision    recall  f1-score   support

      Normal       1.00      1.00      1.00       123
       Type1       1.00      1.00      1.00        35
       Type2       1.00      1.00      1.00        44

    accuracy                           1.00       202
   macro avg       1.00      1.00      1.00       202
weighted avg       1.00      1.00      1.00       202

confusion matrix: 
 [[146   0   0]
 [  0  29   0]
 [  0   0  27]]
              precision    recall  f1-sc

In [17]:
cek = [[31,5.2,6.8,10.9,4.2,33]]
print("model rf")
print(model_rf.predict(cek))

model rf
['Normal']


In [19]:
#DUMP MODEL
pickle.dump(model_rf, open('model_rf.pkl','wb'))